apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-app
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: my-app
    template:
      metadata:
        labels:
          app: my-app
      spec:
        containers:
        - name: my-app-container
          image: my-app:v1
          ports:
          - containerPort: 8080
         imagePullsecrets: myapp-secrets

 envFrom:
   - configMapRef:
       name: my-app-config

 env:
   - name: APP_ENV
      valueFrom:
        configMapRef:
          name:my-app-config
          key:APP_ENV

   - name: LABEL
      valueFrom:
        configMapRef:
          name:my-app-config
          key:APP_LABEL

volumeMounts:
  - name: config-volume
    mountPath: /etc/config
  

volume:
  - name: config-volume
    configMap:
      name: my-app-config
       

   
   
